### ISSUE TITLE
Adding Evernote Tags

### ISSUE THREAD

**Issue by bendrick92** [tgig/Gnotes#1]
Is there currently a way to add tags through the Dropbox .md file and have them show up on my note in Evernote?

**Comment by tgig** [comment]
Hey, sorry for the delay. For some reason I was not getting these notifications. This is not currently built in, but I should make it happen. Will try to get to it soon.

**Comment by tgig** [comment]
@bendrick92: You can now add tags by using a YAML header on a note, like this:

```
---
title: This is the note title
tags:
   - tag1
   - tag2
   - tag3
---

This is the note body.
```
