### ISSUE TITLE
Changing Notebooks

### ISSUE THREAD

**Issue by rrawb** [tgig/Gnotes#2]
Along with the addition of tags, is there a way to select which notebook the service sends it to?

**Comment by tgig** [comment]
Hey, sorry for the delay. For some reason I was not getting these notifications. This is not currently built in, but I will try to make it happen along with Issue #1. Will try to get to it soon.

**Comment by tgig** [comment]
I looked into this request and discovered it is a more in-depth task than I want to undertake for this project. To make it work, I must pass a notebook guid (not just a notebook name) which has a lot of consequences for the user interface. If you want to submit a pull request that's cool, but I'm not going to implement this request atm.
