### ISSUE TITLE
Blockquotes

### ISSUE THREAD

**Issue by shadoworth** [tgig/Gnotes#3]
Hi,
the connection from dropbox to evernote works great for me, thanks!

The only issue that I'm experiencing is with blockquotes:

This:
```
> Attendees  
```
is not converted into 
> Attendees  

Can you please verify?

**Comment by tgig** [comment]
Confirmed on my side as well.

I use the Marked library for Markdown-to-HTML conversion.
https://github.com/chjj/marked

There is a recent Issue, and a history of issues with blockquote rendering:
https://github.com/chjj/marked/issues?utf8=%E2%9C%93&q=blockquote

Not much I can do. Sorry!

**Comment by tgig** [comment]
Problem is with library, not much can be done on my side. Closing.
