### ISSUE TITLE
Blockquotes

### ISSUE THREAD

**Issue by masonchumpia** [tgig/Gnotes#4]
Markdown blockquotes (greater than sign at the beginning of each line) don't seem to be working correctly at the moment through Gnotes. I generated the same note using Markable, another Markdown-to-Evernote service, and the blockquote looks correct using that method.

**Comment by tgig** [comment]
Gnotes is currently unavailable, needs to be updated to the latest version of the Evernote API as mentioned in Issue #8. This issue is being closed for now, can be reopened if Gnotes is ever reactivated.
