### ISSUE TITLE
How to input the .md file in specific notebook in Evernote

### ISSUE THREAD

**Issue by JonghyeokPark** [tgig/Gnotes#6]
First of all, Thanks for great works for markdown editor in Evernote : )
Maybe I missed the instructions in the manual, how to assign the ".md file" to specific notebook in Evernote ?
More specifically, in the case of title, first line in ".md file" will be the title in Evernote, however how to assign the specific notebook?

**Comment by tgig** [comment]
Hi there, there is currently no way to choose which notebook the note goes into. It will always go into your default notebook. If you want to create a pull request using a YAML header to determine the notebook, that would be cool 👍
