### ISSUE TITLE
notes.giggy.com disconnected by Evernote

### ISSUE THREAD

**Issue by heydonkey** [tgig/Gnotes#7]
I've tried to set it up again but the page sits at "Please Wait" when connecting to Dropbox - can't get to the part where I can re-set up Evernote.

![screen shot 2018-09-08 at 4 20 35 pm](https://user-images.githubusercontent.com/7155183/45250240-235a2c80-b383-11e8-973d-b0db56f18abe.png)

Any ideas?

**Comment by tgig** [comment]
Thanks, I'll look into it as soon as possible

**Comment by heydonkey** [comment]
Thank you Travis - much appreciated. ☺️

| Carpe Aptenodytes (Seize the Penguin) | http://www.getgnulinux.org/

Surfing is a good choice for people who like skateboarding but wish it had more sharks.

**Comment by tgig** [comment]
Hi heydonkey, just an update from my side. I have not been able to get to this fix. It's probably not complicated, I'm just seem to have _negative hours in the day_ lately. I created a new Issue #8 if you want to update the Evernote API and make a pull request. Not sure when I'm going to be able to get to it...

**Comment by heydonkey** [comment]
No worries at all - thanks Travis - much appreciated.

| Carpe Aptenodytes (Seize the Penguin) | http://www.getgnulinux.org/

Surfing is a good choice for people who like skateboarding but wish it had more sharks.
